INSERT INTO states (id, code, name, url_slug_path)
VALUES
  (1,1,'Aguascalientes','aguascalientes'),
  (2,2,'Baja California','baja-california'),
  (3,3,'Baja California Sur','baja-california-sur'),
  (4,4,'Campeche','campeche'),
  (5,5,'Coahuila','coahuila'),
  (6,6,'Colima','colima'),
  (7,7,'Chiapas','chiapas'),
  (8,8,'Chihuahua','chihuahua'),
  (9,9,'Ciudad de México','ciudad-de-mexico'),
  (10,10,'Durango','durango'),
  (11,11,'Guanajuato','guanajuato'),
  (12,12,'Guerrero','guerrero'),
  (13,13,'Hidalgo','hidalgo'),
  (14,14,'Jalisco','jalisco'),
  (15,15,'México','mexico'),
  (16,16,'Michoacán','michoacan'),
  (17,17,'Morelos','morelos'),
  (18,18,'Nayarit','nayarit'),
  (19,19,'Nuevo León','nuevo-leon'),
  (20,20,'Oaxaca','oaxaca'),
  (21,21,'Puebla','puebla'),
  (22,22,'Querétaro','queretaro'),
  (23,23,'Quintana Roo','quintana-roo'),
  (24,24,'San Luis Potosí','san-luis-potosi'),
  (25,25,'Sinaloa','sinaloa'),
  (26,26,'Sonora','sonora'),
  (27,27,'Tabasco','tabasco'),
  (28,28,'Tamaulipas','tamaulipas'),
  (29,29,'Tlaxcala','tlaxcala'),
  (30,30,'Veracruz','veracruz'),
  (31,31,'Yucatán','yucatan'),
  (32,32,'Zacatecas','zacatecas')